component MemoryTile inherits Rectangle {
    callback clicked;
    in property <bool> open_curtain;
    in property <bool> solved;
    in property <image> icon;

    height: 64px;
    width: 64px;
    background: solved ? #34CE57 : #3960D5;
    animate background { duration: 800ms; }

    Image {
        source: icon;
        width: parent.width;
        height: parent.height;
    }

    // Left curtain
    Rectangle {
        background: #193076;
        width: open_curtain ? 0px : (parent.width / 2);
        height: parent.height;
        animate width { duration: 250ms; easing: ease-in; }
    }

    // Right curtain
    Rectangle {
        background: #193076;
        x: open_curtain ? parent.width : (parent.width / 2);
        width: open_curtain ? 0px : (parent.width / 2);
        height: parent.height;
        animate width { duration: 250ms; easing: ease-in; }
        animate x { duration: 250ms; easing: ease-in; }
    }

    TouchArea {
        clicked => {
            // Delegate to the user of this element
            root.clicked();
        }
    }
}

component LeftPanel inherits Rectangle {
    min-width: 200px;
    background: blue;
    VerticalLayout {
        width: parent.width;
        alignment: start;
        Rectangle {
            Text { text: "test";}
        }
        Rectangle {
            Text { text: "test";}
        }
    }
}

component Page inherits Rectangle {
    min-width: 600px;
    background: red;
}

export component MainWindow inherits Window {
    title: "RustyUp";
    in-out property <length> custom_min_height: 200px;
    min-height: custom_min_height;
    Rectangle {
        HorizontalLayout {
            LeftPanel {}
            Page {}
        }
    }
}
